---
deployment:
  tasks:
    - export PATH="$PATH:/opt/alt/alt-nodejs16/root/usr/bin/"
    - cd /home/cayi7350/thecasinos.com
    - git pull
    - /opt/cpanel/composer/bin/composer install
    - npm install
