---
deployment:
  tasks:
    - export PATH="$PATH:/opt/alt/alt-nodejs16/root/usr/bin/"
    - cd /home/cayi7350/thecasinos.com
    - git reset --hard origin/master
    - git pull
    - /opt/cpanel/composer/bin/composer install
    - /opt/alt/alt-nodejs16/root/usr/bin/npm install
    - /opt/alt/alt-nodejs16/root/usr/bin/npm run build
    - /bin/php artisan app:clean


