---
deployment:
  tasks:
    - export PATH="$PATH:/opt/alt/alt-nodejs16/root/usr/bin/"
    - cd /home/cayi7350/thecasinos.com
    - git pull
    - composer install
    - npm install
    - npm run build
    - php artisan app:clean
