import type { Casino, Destination, OnlineCasino } from './types';

export const fallbackCasinos: Casino[] = [
  {
    id: 664,
    legacy_id: 664,
    name: 'Casino de Montréal',
    slug: 'casino-montreal',
    country_name: 'Canada',
    country_slug: 'canada',
    city_name: 'Montréal',
    city_slug: 'montreal',
    state_name: 'Quebec',
    short_description: 'Elegance & Excitement',
    description: 'Casino Montreal: where elegance meets adventure, and strategy meets luck.',
    opened_on: '1993-10-09',
    gaming_machines: 3000,
    poker_tables: 26,
    table_games: 9,
    square_footage: 526488,
    has_slots: true,
    has_table_games: true,
    latitude: 45.5054701,
    longitude: -73.5256318,
    published: true,
  },
  {
    id: 457,
    legacy_id: 457,
    name: 'Bellagio Hotel and Casino',
    slug: 'bellagio-hotel-and-casino',
    country_name: 'United States',
    country_slug: 'united-states',
    city_name: 'Las Vegas',
    city_slug: 'las-vegas',
    state_name: 'Nevada',
    short_description: 'Elegance & Excitement',
    description: 'Bellagio Casino: a luxurious world of gaming in the heart of Las Vegas.',
    opened_on: '1998-10-15',
    gaming_machines: 2300,
    poker_tables: 40,
    table_games: 80,
    square_footage: 100000,
    always_open: true,
    has_sportsbook: true,
    has_slots: true,
    latitude: 36.1129455,
    longitude: -115.1765067,
    published: true,
  },
  {
    id: 1595,
    legacy_id: 1595,
    name: 'Casino de Monte-Carlo',
    slug: 'casino-de-monte-carlo',
    country_name: 'Monaco',
    country_slug: 'monaco',
    city_name: 'Monte-Carlo',
    city_slug: 'monte-carlo',
    short_description: 'Elegance & Gaming',
    description: 'Casino de Monte-Carlo: a timeless beacon of elegance offering a unique gaming experience.',
    opened_on: '1863-01-01',
    gaming_machines: 140,
    square_footage: 108000,
    always_open: true,
    has_slots: true,
    has_table_games: true,
    latitude: 43.7390972,
    longitude: 7.4280681,
    published: true,
  },
  {
    id: 1133,
    legacy_id: 1133,
    name: 'Marina Bay Sands Casino',
    slug: 'marina-bay-sands-casino',
    country_name: 'Singapore',
    country_slug: 'singapore',
    city_name: 'Marina Bay',
    city_slug: 'marina-bay',
    short_description: 'Elegance & Entertainment',
    description: 'Marina Bay Sands Casino: where luxury meets gaming exhilaration.',
    opened_on: '2010-04-27',
    gaming_machines: 2500,
    square_footage: 160000,
    always_open: true,
    has_slots: true,
    has_table_games: true,
    latitude: 1.2830096,
    longitude: 103.8578751,
    published: true,
  },
  {
    id: 1132,
    legacy_id: 1132,
    name: 'The Venetian Macao',
    slug: 'the-venetian-macao',
    country_name: 'Macau',
    country_slug: 'macau',
    city_name: 'Cotai',
    city_slug: 'cotai',
    short_description: 'Elegance & Thrill',
    description: "Unmatched luxury and gaming in Cotai's Venetian Macao.",
    opened_on: '2007-08-28',
    gaming_machines: 3400,
    poker_tables: 33,
    table_games: 200,
    square_footage: 550000,
    always_open: true,
    has_slots: true,
    has_table_games: true,
    latitude: 22.1500829,
    longitude: 113.5533597,
    published: true,
  },
];

export const fallbackOnlineCasinos: OnlineCasino[] = [
  {
    id: '00000000-0000-4000-8000-000000000001',
    position: 1,
    name: 'DuckyLuck',
    slug: 'DuckyLuck-Casino',
    subtitle: 'A quack above the rest in online gaming',
    rating: 4.9,
    bonus: '500% Welcome Bonus up to $7,500',
    summary: 'Over 400 games, modern payment methods and a broad promotional programme.',
    description: 'DuckyLuck combines slot games, live dealers and cryptocurrency payments in a mobile-friendly experience.',
    bonus_description: 'Welcome offer, daily free spins, cashback and loyalty rewards. Always verify the current terms on the operator website.',
    deposit_description: 'Traditional cards and selected cryptocurrencies are supported.',
    contact_description: 'Support is presented as available by live chat and email.',
    affiliate_url: 'https://get.duckyluck.ag/',
    key_features: ['400+ games', 'Live dealers', 'Crypto payments', 'Mobile compatible'],
    pros: ['Extensive game library', 'Generous promotions', 'Multiple payment options'],
    cons: ['Limited table games', 'No sports betting', 'Young platform'],
    deposit_methods: ['Bitcoin', 'Mastercard', 'Visa'],
    contact_methods: ['Live chat', 'Email'],
    active: true,
    published: true,
  },
  {
    id: '00000000-0000-4000-8000-000000000002',
    position: 2,
    name: 'Wild Casino',
    slug: 'Wild-Casino',
    subtitle: 'A broad catalogue with live dealer games',
    rating: 4.1,
    bonus: '100% welcome bonus up to $5,000',
    summary: 'A wide game selection with traditional and cryptocurrency banking options.',
    description: 'Wild Casino brings together slots, table games and a live dealer catalogue across desktop and mobile.',
    bonus_description: 'Welcome and recurring promotions are offered subject to the operator’s eligibility and wagering rules.',
    deposit_description: 'Cards, bank transfers and selected cryptocurrencies are listed as payment methods.',
    contact_description: 'Support is available through chat, email and telephone according to the operator.',
    affiliate_url: 'https://record.commissionkings.ag/',
    key_features: ['400+ games', 'Live dealer', 'Crypto banking', '24/7 support'],
    pros: ['Wide game variety', 'Flexible payment options', 'Mobile-friendly'],
    cons: ['No demo mode', 'Fees on some withdrawals', 'No sportsbook'],
    deposit_methods: ['Bitcoin', 'Visa', 'Mastercard', 'Bank transfer'],
    contact_methods: ['Live chat', 'Email', 'Phone'],
    active: true,
    published: true,
  },
  {
    id: '00000000-0000-4000-8000-000000000003',
    position: 3,
    name: 'LuckyBird',
    slug: 'LuckyBird-Casino',
    subtitle: 'Crypto-first games and competitions',
    rating: 4.5,
    bonus: 'Free chance to win BTC/ETH/USDT',
    summary: 'Exclusive games, daily contests and cryptocurrency transactions.',
    description: 'LuckyBird focuses on an original game catalogue and a cryptocurrency-led payment experience.',
    bonus_description: 'No-deposit mechanics and recurring contests may be available; current operator terms apply.',
    deposit_description: 'The platform primarily supports cryptocurrencies.',
    contact_description: 'Multilingual assistance is advertised through live chat and email.',
    affiliate_url: 'https://luckybird.vip/',
    key_features: ['Exclusive games', 'Crypto payments', 'Daily contests', 'VIP programme'],
    pros: ['Original game selection', 'Fast crypto payments', 'High stated payout rate'],
    cons: ['Limited catalogue', 'Crypto-only focus', 'No classic table games'],
    deposit_methods: ['Bitcoin', 'Litecoin', 'Ethereum'],
    contact_methods: ['Live chat', 'Email'],
    active: true,
    published: true,
  },
  {
    id: '00000000-0000-4000-8000-000000000004',
    position: 4,
    name: 'Red Dog',
    slug: 'Red-Dog-Casino',
    subtitle: 'Classic games with cryptocurrency support',
    rating: 4.8,
    bonus: '225% Welcome Bonus + 20% BTC Deposit',
    summary: 'Slots, free demo mode and multiple cryptocurrency options.',
    description: 'Red Dog offers a compact casino catalogue with a strong focus on slots and crypto payments.',
    bonus_description: 'Welcome promotions are subject to operator restrictions and wagering requirements.',
    deposit_description: 'Cards and several cryptocurrencies are supported.',
    contact_description: 'The operator lists round-the-clock customer assistance.',
    affiliate_url: 'https://record.toponepartners.com/',
    key_features: ['150+ games', 'Demo mode', 'Crypto support', 'Mobile compatible'],
    pros: ['Easy navigation', 'Demo play', 'Multiple crypto options'],
    cons: ['Smaller catalogue', 'Limited live games', 'Regional restrictions'],
    deposit_methods: ['Bitcoin', 'Cards', 'Cryptocurrency'],
    contact_methods: ['Live chat', 'Email'],
    active: true,
    published: true,
  },
  {
    id: '00000000-0000-4000-8000-000000000005',
    position: 5,
    name: 'Stake Casino',
    slug: 'Stake-Casino',
    subtitle: 'Social casino experience',
    rating: 4.6,
    bonus: '$25 No Deposit, 250,000 Gold Coins',
    summary: 'A social gaming offer with a large catalogue and frequent promotions.',
    affiliate_url: 'https://stake.com/',
    key_features: ['Social games', 'Mobile play', 'Promotions'],
    pros: ['Large catalogue', 'Simple onboarding', 'Mobile experience'],
    cons: ['Availability varies', 'Terms vary by region'],
    deposit_methods: ['Operator-specific methods'],
    contact_methods: ['Help centre'],
    active: true,
    published: true,
  },
  {
    id: '00000000-0000-4000-8000-000000000006',
    position: 6,
    name: 'High 5 Casino',
    slug: 'High-5-Casino',
    subtitle: 'Social casino with daily rewards',
    rating: 4.4,
    bonus: '600 Diamonds and 250 Game Coins',
    summary: 'A social casino catalogue built around virtual currencies and recurring rewards.',
    affiliate_url: 'https://record.high5affiliates.com/',
    key_features: ['Social casino', 'Daily rewards', 'Mobile play'],
    pros: ['Accessible experience', 'Frequent rewards', 'Large slot selection'],
    cons: ['Virtual currency model', 'Regional availability'],
    deposit_methods: ['Operator-specific methods'],
    contact_methods: ['Help centre'],
    active: true,
    published: true,
  },
];

export const fallbackDestinations: Destination[] = [
  { country_name: 'United States', country_slug: 'united-states', casino_count: 2154 },
  { country_name: 'Canada', country_slug: 'canada', casino_count: 410 },
  { country_name: 'France', country_slug: 'france', casino_count: 203 },
  { country_name: 'United Kingdom', country_slug: 'united-kingdom', casino_count: 171 },
  { country_name: 'Australia', country_slug: 'australia', casino_count: 167 },
  { country_name: 'Mexico', country_slug: 'mexico', casino_count: 153 },
];
