export type Casino = {
  id: string | number;
  legacy_id?: number | null;
  name: string;
  slug: string;
  country_name: string;
  country_slug: string;
  city_name: string;
  city_slug: string;
  state_name?: string | null;
  short_description?: string | null;
  description?: string | null;
  editorial_title?: string | null;
  editorial_paragraphs?: string[];
  summary?: string | null;
  games_description?: string | null;
  fun_facts?: string | null;
  seo_title?: string | null;
  seo_description?: string | null;
  seo_keywords?: string | null;
  opened_on?: string | null;
  gaming_machines?: number | null;
  poker_tables?: number | null;
  table_games?: number | null;
  square_footage?: number | null;
  hotel_name?: string | null;
  owner_name?: string | null;
  always_open?: boolean | null;
  has_sportsbook?: boolean;
  has_bingo?: boolean;
  has_slots?: boolean;
  has_table_games?: boolean;
  longitude?: number | null;
  latitude?: number | null;
  legacy_image_name?: string | null;
  has_original_image?: boolean;
  published?: boolean;
};

export type OnlineCasino = {
  id: string | number;
  position: number | null;
  name: string;
  slug: string;
  subtitle?: string | null;
  rating: number;
  bonus: string;
  summary: string;
  description?: string | null;
  bonus_description?: string | null;
  deposit_description?: string | null;
  contact_description?: string | null;
  affiliate_url: string;
  website_url?: string | null;
  logo_url?: string | null;
  operator_name?: string | null;
  operator_status?: 'active' | 'restricted' | 'unavailable' | 'monitoring';
  casino_type?: 'real-money' | 'sweepstakes' | 'social';
  established_year?: number | null;
  license_authority?: string | null;
  license_number?: string | null;
  license_url?: string | null;
  key_features: string[];
  pros: string[];
  cons: string[];
  deposit_methods: string[];
  withdrawal_methods?: string[];
  contact_methods: string[];
  supported_regions?: string[];
  restricted_regions?: string[];
  currencies?: string[];
  game_types?: string[];
  software_providers?: string[];
  languages?: string[];
  security_features?: string[];
  responsible_gambling_tools?: string[];
  game_count?: number | null;
  minimum_deposit?: string | null;
  minimum_withdrawal?: string | null;
  withdrawal_time?: string | null;
  wagering_requirement?: string | null;
  kyc_requirements?: string | null;
  mobile_support?: string | null;
  support_hours?: string | null;
  support_email?: string | null;
  ios_url?: string | null;
  android_url?: string | null;
  games_description?: string | null;
  withdrawal_description?: string | null;
  security_description?: string | null;
  mobile_description?: string | null;
  verdict?: string | null;
  rating_games?: number | null;
  rating_payments?: number | null;
  rating_withdrawals?: number | null;
  rating_support?: number | null;
  rating_safety?: number | null;
  rating_mobile?: number | null;
  screenshots?: { url: string; alt?: string; caption?: string }[];
  faqs?: { question: string; answer: string }[];
  source_urls?: string[];
  seo_title?: string | null;
  seo_description?: string | null;
  cta_label?: string | null;
  reviewed_at?: string | null;
  last_verified_at?: string | null;
  active: boolean;
  published: boolean;
  affiliate_disclosure?: string | null;
};

export type Destination = {
  country_name: string;
  country_slug: string;
  casino_count: number;
};
