alter table public.online_casinos
  add column if not exists website_url text not null default '',
  add column if not exists operator_name text,
  add column if not exists operator_status text not null default 'active',
  add column if not exists casino_type text not null default 'real-money',
  add column if not exists established_year smallint,
  add column if not exists license_authority text,
  add column if not exists license_number text,
  add column if not exists license_url text,
  add column if not exists supported_regions text[] not null default '{}',
  add column if not exists restricted_regions text[] not null default '{}',
  add column if not exists currencies text[] not null default '{}',
  add column if not exists withdrawal_methods text[] not null default '{}',
  add column if not exists game_types text[] not null default '{}',
  add column if not exists software_providers text[] not null default '{}',
  add column if not exists languages text[] not null default '{}',
  add column if not exists security_features text[] not null default '{}',
  add column if not exists responsible_gambling_tools text[] not null default '{}',
  add column if not exists game_count integer,
  add column if not exists minimum_deposit text,
  add column if not exists minimum_withdrawal text,
  add column if not exists withdrawal_time text,
  add column if not exists wagering_requirement text,
  add column if not exists kyc_requirements text,
  add column if not exists mobile_support text,
  add column if not exists support_hours text,
  add column if not exists support_email text,
  add column if not exists ios_url text,
  add column if not exists android_url text,
  add column if not exists games_description text,
  add column if not exists withdrawal_description text,
  add column if not exists security_description text,
  add column if not exists mobile_description text,
  add column if not exists verdict text,
  add column if not exists rating_games numeric(2,1),
  add column if not exists rating_payments numeric(2,1),
  add column if not exists rating_withdrawals numeric(2,1),
  add column if not exists rating_support numeric(2,1),
  add column if not exists rating_safety numeric(2,1),
  add column if not exists rating_mobile numeric(2,1),
  add column if not exists screenshots jsonb not null default '[]'::jsonb,
  add column if not exists faqs jsonb not null default '[]'::jsonb,
  add column if not exists source_urls text[] not null default '{}',
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists cta_label text not null default 'Visit site',
  add column if not exists reviewed_at date,
  add column if not exists last_verified_at timestamptz;

alter table public.online_casinos
  drop constraint if exists online_casinos_operator_status_check,
  add constraint online_casinos_operator_status_check
    check (operator_status in ('active', 'restricted', 'unavailable', 'monitoring')),
  drop constraint if exists online_casinos_casino_type_check,
  add constraint online_casinos_casino_type_check
    check (casino_type in ('real-money', 'sweepstakes', 'social')),
  drop constraint if exists online_casinos_established_year_check,
  add constraint online_casinos_established_year_check
    check (established_year is null or established_year between 1900 and 2100),
  drop constraint if exists online_casinos_game_count_check,
  add constraint online_casinos_game_count_check
    check (game_count is null or game_count >= 0),
  drop constraint if exists online_casinos_screenshots_check,
  add constraint online_casinos_screenshots_check
    check (jsonb_typeof(screenshots) = 'array'),
  drop constraint if exists online_casinos_faqs_check,
  add constraint online_casinos_faqs_check
    check (jsonb_typeof(faqs) = 'array'),
  drop constraint if exists online_casinos_rating_games_check,
  add constraint online_casinos_rating_games_check
    check (rating_games is null or rating_games between 0 and 5),
  drop constraint if exists online_casinos_rating_payments_check,
  add constraint online_casinos_rating_payments_check
    check (rating_payments is null or rating_payments between 0 and 5),
  drop constraint if exists online_casinos_rating_withdrawals_check,
  add constraint online_casinos_rating_withdrawals_check
    check (rating_withdrawals is null or rating_withdrawals between 0 and 5),
  drop constraint if exists online_casinos_rating_support_check,
  add constraint online_casinos_rating_support_check
    check (rating_support is null or rating_support between 0 and 5),
  drop constraint if exists online_casinos_rating_safety_check,
  add constraint online_casinos_rating_safety_check
    check (rating_safety is null or rating_safety between 0 and 5),
  drop constraint if exists online_casinos_rating_mobile_check,
  add constraint online_casinos_rating_mobile_check
    check (rating_mobile is null or rating_mobile between 0 and 5);

comment on column public.online_casinos.website_url is 'Official operator URL. Keep separate from affiliate_url.';
comment on column public.online_casinos.screenshots is 'Array of objects with url, alt and caption fields.';
comment on column public.online_casinos.faqs is 'Array of objects with question and answer fields.';
comment on column public.online_casinos.source_urls is 'Editorial verification sources; official sources should come first.';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'review-media',
  'review-media',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists review_media_admin_select on storage.objects;
create policy review_media_admin_select on storage.objects
  for select to authenticated
  using (bucket_id = 'review-media' and (select private.is_admin()));

drop policy if exists review_media_admin_insert on storage.objects;
create policy review_media_admin_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'review-media' and (select private.is_admin()));

drop policy if exists review_media_admin_update on storage.objects;
create policy review_media_admin_update on storage.objects
  for update to authenticated
  using (bucket_id = 'review-media' and (select private.is_admin()))
  with check (bucket_id = 'review-media' and (select private.is_admin()));

drop policy if exists review_media_admin_delete on storage.objects;
create policy review_media_admin_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'review-media' and (select private.is_admin()));

update public.online_casinos
set
  position = 1,
  rating = 3.2,
  subtitle = 'Large offshore lobby with crypto-friendly banking',
  bonus = '500% welcome bonus up to $2,500',
  summary = 'DuckyLuck offers more than 500 browser games, practice play and crypto banking, but its Costa Rica registration provides less player protection than a tier-one gambling licence.',
  description = 'Launched in 2020, DuckyLuck is an offshore real-money casino aimed mainly at North American players. Its lobby covers slots, table games, video poker, jackpots, live casino titles and original games without requiring a download.\n\nThe operator is transparent about a $25 entry point and publishes separate banking, withdrawal and bonus terms. The main trade-off is regulatory: the site references Costa Rica registration rather than a licence from a regulator such as the UKGC or MGA. Players should therefore verify local legality, complete KYC before cashing out and read every promotion before depositing.',
  bonus_description = 'The official site currently promotes a 500% welcome package up to $2,500. The value is split across qualifying deposits and the playthrough, eligible games, maximum bet and cashout rules depend on the selected offer. Check the cashier terms before opting in.',
  deposit_description = 'The cashier combines cards, bank options and several cryptocurrencies. The official banking page displays a $25 minimum deposit, although available methods vary by country and account.',
  withdrawal_description = 'Verified withdrawals are normally reviewed before release. The operator states a 48–72 hour authorisation target for verified accounts; crypto delivery can be faster, while checks and bank wires carry higher minimums, fees and delivery times.',
  contact_description = 'Support is available through live chat, email and the account ticket centre. Identity documents may be requested before a first withdrawal.',
  security_description = 'SSL transport and account verification are standard. DuckyLuck links to responsible-gambling help, but its Costa Rica registration does not provide the same complaint and fund-protection framework as stronger regulated markets.',
  mobile_description = 'The complete browser lobby is responsive on mobile and does not require an app download. Practice mode is available on eligible games.',
  verdict = 'A broad, easy-to-use offshore casino for players who prioritise crypto and game variety. The weaker regulatory framework and slower, fee-bearing fiat withdrawals keep it below the highest-rated regulated operators.',
  website_url = 'https://www.duckyluck.ag/',
  affiliate_url = 'https://www.duckyluck.ag/',
  operator_name = 'Online Casino Share group',
  operator_status = 'active',
  casino_type = 'real-money',
  established_year = 2020,
  license_authority = 'Costa Rica operator registration',
  license_number = null,
  license_url = 'https://www.duckyluck.ag/faq/terms-and-conditions/',
  supported_regions = array['United States where permitted', 'Canada where permitted', 'Other eligible international jurisdictions'],
  restricted_regions = array['Jurisdictions where offshore gambling is prohibited'],
  currencies = array['USD', 'BTC', 'ETH', 'LTC'],
  deposit_methods = array['Visa', 'Mastercard', 'Bitcoin', 'Ethereum', 'Litecoin', 'Bank wire'],
  withdrawal_methods = array['Cryptocurrency', 'Bank wire', 'Paper check'],
  game_types = array['Slots', 'Live casino', 'Table games', 'Video poker', 'Jackpots', 'Originals'],
  software_providers = array['Multiple third-party studios; verify the current lobby'],
  languages = array['English'],
  security_features = array['SSL encryption', 'Identity verification', 'Transaction review'],
  responsible_gambling_tools = array['Responsible-gambling information', 'GamCare link', 'Support-assisted account closure'],
  game_count = 500,
  minimum_deposit = '$25 or crypto equivalent',
  minimum_withdrawal = 'Method-dependent; checks start at $150',
  withdrawal_time = '48–72 hour approval target; delivery depends on method',
  wagering_requirement = 'Promotion-dependent; deposits must be wagered at least 1x before withdrawal',
  kyc_requirements = 'Identity and payment verification before or during withdrawal review',
  mobile_support = 'Responsive browser; no download required',
  support_hours = '24/7 help centre and live chat advertised',
  support_email = 'support@duckyluck.ag',
  key_features = array['500+ browser games', 'Practice mode', 'Crypto deposits and withdrawals', 'Live casino and jackpots'],
  pros = array['Broad game catalogue', 'Low published deposit minimum', 'Crypto and fiat cashier', 'Mobile browser works without an app'],
  cons = array['No tier-one gambling licence', 'Fiat withdrawals can carry fees and longer waits', 'Bonus rules vary by promotion', 'Availability depends on local law'],
  rating_games = 4.1,
  rating_payments = 3.6,
  rating_withdrawals = 2.8,
  rating_support = 3.5,
  rating_safety = 2.1,
  rating_mobile = 4.0,
  faqs = '[{"question":"Is DuckyLuck licensed?","answer":"The site identifies a Costa Rica operator registration. This is not equivalent to a UKGC or MGA licence and offers more limited player recourse."},{"question":"What is the minimum deposit?","answer":"The official banking page displays a $25 minimum, with methods and limits varying by location."},{"question":"How long do withdrawals take?","answer":"The operator states a 48–72 hour approval target for verified accounts. Final delivery is method-dependent and fiat options can take longer."}]'::jsonb,
  source_urls = array['https://www.duckyluck.ag/','https://www.duckyluck.ag/banking/','https://www.duckyluck.ag/faq/terms-and-conditions/','https://www.duckyluck.ag/faq/about-withdrawing/'],
  seo_title = 'DuckyLuck Casino review: games, payments and withdrawals',
  seo_description = 'Independent DuckyLuck review covering its 500+ games, $25 deposit minimum, crypto banking, withdrawal process and Costa Rica registration.',
  cta_label = 'Visit DuckyLuck',
  reviewed_at = date '2026-08-03',
  last_verified_at = timestamptz '2026-08-03 00:00:00+00',
  active = true,
  published = true
where slug = 'DuckyLuck-Casino';

update public.online_casinos
set
  position = 2,
  rating = 3.7,
  subtitle = 'Deep game catalogue and fast crypto withdrawals',
  bonus = 'Welcome package up to $5,000; current terms apply',
  summary = 'Wild Casino combines 800+ slots, live dealer tables, extensive crypto banking and 24/7 support, with the usual jurisdiction and regulatory caveats of an offshore operator.',
  description = 'Wild Casino is a browser-based offshore casino with a particularly broad slots catalogue, table games, video poker and live dealer studios. The interface works across desktop and mobile, and the operator publishes detailed help articles for banking, withdrawals and account security.\n\nIts strongest operational feature is the cashier: cards are supported for deposits and a long list of cryptocurrencies can be used for withdrawals. The trade-off is that alternative fiat withdrawals are slower and more expensive, while licence and complaint information is less clear than on fully regulated domestic sites.',
  bonus_description = 'Welcome and recurring promotions change by account and location. Always compare the headline value with the playthrough, maximum bet, eligible games, expiry and withdrawal rules displayed in the cashier.',
  deposit_description = 'Instant card deposits and multiple cryptocurrencies are supported. The exact minimum, fee and eligibility depend on the selected method and location.',
  withdrawal_description = 'The official withdrawal table lists many crypto methods from $20 with processing advertised within 24 hours. Wire transfer, check, money order and person-to-person options have higher minimums, fees and longer processing windows.',
  contact_description = 'Live chat and email support are advertised around the clock. The account security centre supports email or SMS two-factor verification.',
  security_description = 'Wild Casino publishes SSL, transaction-review and two-factor-authentication information. Its offshore framework still gives players less independent recourse than a locally licensed operator.',
  mobile_description = 'The responsive web lobby runs without a download. An iOS listing is also available in selected regions, while browser play remains the most universal option.',
  verdict = 'A strong games-and-banking proposition for crypto-oriented players who understand offshore risk. Fast published crypto cashout targets and 2FA are positives; regulatory transparency and expensive fiat exits are the main weaknesses.',
  website_url = 'https://www.wildcasino.ag/',
  affiliate_url = 'https://www.wildcasino.ag/',
  operator_name = 'Wild Casino',
  operator_status = 'active',
  casino_type = 'real-money',
  established_year = 2017,
  license_authority = 'Offshore operator; verify current licence on the official site',
  license_number = null,
  license_url = 'https://help.wildcasino.ag/en/articles/201358-terms-and-conditions',
  supported_regions = array['United States where permitted', 'Canada where permitted', 'Other eligible international jurisdictions'],
  restricted_regions = array['Jurisdictions where offshore gambling is prohibited'],
  currencies = array['USD', 'BTC', 'ETH', 'LTC', 'USDT', 'USDC', 'DOGE', 'XRP'],
  deposit_methods = array['Visa', 'Mastercard', 'Bitcoin', 'Ethereum', 'Litecoin', 'USDT', 'USDC'],
  withdrawal_methods = array['Cryptocurrency', 'Wire transfer', 'Check by courier', 'Money order', 'Person to person'],
  game_types = array['Slots', 'Live dealer', 'Blackjack', 'Roulette', 'Table games', 'Video poker'],
  software_providers = array['Betsoft', 'Nucleus Gaming', 'Visionary iGaming', 'Additional lobby providers'],
  languages = array['English'],
  security_features = array['SSL encryption', 'Email or SMS 2FA', 'Identity verification', 'Recorded game transactions'],
  responsible_gambling_tools = array['Self-exclusion through support', 'Account closure', 'Responsible-gambling guidance'],
  game_count = 800,
  minimum_deposit = 'Method-dependent',
  minimum_withdrawal = '$20 for many cryptocurrencies',
  withdrawal_time = 'Within 24 hours for many crypto methods; 5–15 business days for several fiat methods',
  wagering_requirement = 'Deposited funds must be wagered at least 1x; bonus requirements vary',
  kyc_requirements = 'Identity and payment verification may be required before withdrawal',
  mobile_support = 'Responsive browser and selected iOS availability',
  support_hours = '24/7',
  support_email = 'help@wildcasinocs.ag',
  key_features = array['800+ slots', 'Live dealer studios', 'Large crypto cashier', 'Optional 2FA', '24/7 support'],
  pros = array['Large and varied lobby', 'Many crypto withdrawal choices', 'Published withdrawal limits and fees', 'Two-factor authentication'],
  cons = array['Offshore regulatory protection', 'Fiat withdrawals can be slow and costly', 'No sportsbook or poker room', 'Terms and availability vary by region'],
  rating_games = 4.4,
  rating_payments = 4.3,
  rating_withdrawals = 3.9,
  rating_support = 4.0,
  rating_safety = 2.7,
  rating_mobile = 4.1,
  faqs = '[{"question":"What is Wild Casino’s fastest withdrawal method?","answer":"The official cashier advertises many crypto withdrawals within 24 hours. Actual timing can be affected by KYC and account review."},{"question":"Does Wild Casino support two-factor authentication?","answer":"Yes. The security centre supports verification codes by email or SMS where available."},{"question":"Are there withdrawal fees?","answer":"Bitcoin is listed as free, while several altcoins and fiat methods have fixed or percentage fees. Check the live cashier before requesting payment."}]'::jsonb,
  source_urls = array['https://www.wildcasino.ag/','https://www.wildcasino.ag/banking','https://help.wildcasino.ag/en/articles/201370-withdrawal-limits-and-fees','https://help.wildcasino.ag/en/articles/754796-how-to-enable-2-factor-authentication-2fa','https://help.wildcasino.ag/en/articles/201358-terms-and-conditions'],
  seo_title = 'Wild Casino review: games, banking, payouts and safety',
  seo_description = 'Wild Casino review covering its 800+ slots, live dealers, crypto cashier, withdrawal limits, 2FA and offshore regulatory trade-offs.',
  cta_label = 'Visit Wild Casino',
  reviewed_at = date '2026-08-03',
  last_verified_at = timestamptz '2026-08-03 00:00:00+00',
  active = true,
  published = true
where slug = 'Wild-Casino';

update public.online_casinos
set
  position = null,
  rating = 2.0,
  subtitle = 'Archived crypto sweepstakes review — availability unconfirmed',
  bonus = 'No current offer verified',
  summary = 'LuckyBird was a crypto-only sweepstakes casino with a broad social game lobby. Its official domain was unavailable during our August 2026 verification, so it is archived and not recommended in the active ranking.',
  description = 'LuckyBird operated as a dual-currency sweepstakes casino rather than a conventional real-money gambling site. Players used Gold Coins for entertainment and Sweeps Cash for prize-eligible play, with purchases and redemptions handled in cryptocurrency.\n\nThe product was notable for original games, slots and social competitions, but its official domain did not respond during our 3 August 2026 review. Independent reports conflict on whether the service has closed or is undergoing extended maintenance. The review remains available for historical context, but registration and payment should not be attempted until the operator publishes a verifiable status update.',
  bonus_description = 'Historical promotions included free Gold Coins and Sweeps Cash for registration and activity. No current offer can be verified while the official service is unavailable.',
  deposit_description = 'Historically, Gold Coin packages and prize redemptions used cryptocurrencies rather than card or bank payments.',
  withdrawal_description = 'Historical redemptions started around 30 Sweeps Cash and were paid in supported cryptocurrencies. Current redemption availability cannot be verified.',
  contact_description = 'Historical channels included ticket support, email and community chat. No current response was verified.',
  security_description = 'Sweepstakes casinos do not use the same gambling-licence model as real-money operators. The larger current risk is operational availability: the official domain did not respond during verification.',
  mobile_description = 'LuckyBird previously offered responsive browser play without a native app.',
  verdict = 'Do not deposit or purchase coins while the operator’s status is unresolved. This review is retained as an archive and LuckyBird has been removed from the active Top 10.',
  website_url = 'https://luckybird.io/',
  affiliate_url = 'https://luckybird.io/',
  operator_name = 'LuckyBird',
  operator_status = 'unavailable',
  casino_type = 'sweepstakes',
  established_year = 2022,
  license_authority = 'Sweepstakes model; no real-money casino licence',
  license_number = null,
  license_url = null,
  supported_regions = array['Historically available in many US states'],
  restricted_regions = array['Current availability unconfirmed'],
  currencies = array['Gold Coins', 'Sweeps Cash', 'BTC', 'ETH', 'DOGE', 'LTC', 'USDT'],
  deposit_methods = array['Cryptocurrency only (historical)'],
  withdrawal_methods = array['Cryptocurrency redemption (historical)'],
  game_types = array['Slots', 'Originals', 'Table games', 'Instant games'],
  software_providers = array['Multiple social-casino studios'],
  languages = array['English'],
  security_features = array['SSL encryption (historical)', 'KYC for prize redemption (historical)'],
  responsible_gambling_tools = array['Sweepstakes rules and eligibility controls (historical)'],
  game_count = 700,
  minimum_deposit = 'No deposit; historical coin packages used crypto',
  minimum_withdrawal = 'Historically 30 Sweeps Cash',
  withdrawal_time = 'Unavailable for verification',
  wagering_requirement = 'Historical sweepstakes playthrough rules applied',
  kyc_requirements = 'Historical identity verification for redemptions',
  mobile_support = 'Historical browser support; no current service verified',
  support_hours = 'Unavailable for verification',
  support_email = null,
  key_features = array['Archived review', 'Crypto-only sweepstakes model', '700+ historical games', 'Operator status warning'],
  pros = array['Historically broad social-game catalogue', 'Original games and community mechanics', 'Multiple crypto assets'],
  cons = array['Official domain unavailable at review time', 'Operator status is unresolved', 'Crypto-only purchase and redemption model', 'No gambling regulator oversight'],
  rating_games = 3.8,
  rating_payments = 2.5,
  rating_withdrawals = 1.0,
  rating_support = 1.0,
  rating_safety = 1.2,
  rating_mobile = 2.0,
  faqs = '[{"question":"Is LuckyBird still operating?","answer":"The official domain was unavailable during our 3 August 2026 check and multiple independent sources report an extended closure. We therefore treat it as unavailable until the operator confirms otherwise."},{"question":"Was LuckyBird a real-money casino?","answer":"No. It used a sweepstakes model with Gold Coins for entertainment and Sweeps Cash for prize-eligible play."},{"question":"Should I send cryptocurrency to LuckyBird?","answer":"No. Do not send funds while the official service and redemption status cannot be verified."}]'::jsonb,
  source_urls = array['https://luckybird.io/','https://www.playusa.com/sweepstakes-casinos/luckybird/','https://sweepskings.com/reviews/luckybird-io/'],
  seo_title = 'LuckyBird Casino status and archived review',
  seo_description = 'Archived LuckyBird review explaining its crypto sweepstakes model and why it is not included in the active ranking while its availability is unconfirmed.',
  cta_label = 'Website unavailable',
  reviewed_at = date '2026-08-03',
  last_verified_at = timestamptz '2026-08-03 00:00:00+00',
  active = false,
  published = false
where slug = 'LuckyBird-Casino';

update public.online_casinos
set
  position = 3,
  rating = 3.4,
  subtitle = 'Large slot lobby, practice play and crypto banking',
  bonus = 'Welcome package up to $8,000; current terms apply',
  summary = 'Red Dog combines roughly 1,600 browser games, extensive practice play and crypto/card banking. Its Anjouan licence and currently empty live-dealer category require a more cautious rating than the old review gave it.',
  description = 'Red Dog is an offshore real-money casino launched in 2019. Its current browser lobby is led by more than 1,300 slots, plus blackjack, video poker, table games, jackpots and speciality titles. Many games include a free-play mode, making it easy to inspect the interface before registering.\n\nThe operator promotes a large multi-deposit welcome package and supports both traditional cards and cryptocurrency. Players should focus on the detailed wagering and withdrawal conditions rather than the headline bonus, and should understand that an Anjouan licence offers less independent protection than tier-one regulated markets.',
  bonus_description = 'The official site currently promotes a welcome package up to $8,000. It is a multi-stage offer with game weighting, playthrough, maximum-bet and withdrawal conditions; check the current terms before accepting it.',
  deposit_description = 'The cashier supports cards and multiple cryptocurrencies. Exact limits and availability depend on location, verification and account history.',
  withdrawal_description = 'Crypto is generally the most practical withdrawal route. Card, bank and alternative methods can involve higher minimums, additional verification and longer processing.',
  contact_description = 'The site advertises 24/7 assistance and provides account support through chat and email channels.',
  security_description = 'The official site states that Red Dog is licensed by the Autonomous Island of Anjouan. SSL and KYC are used, but player recourse is weaker than under domestic regulators.',
  mobile_description = 'All core lobby categories run in a responsive browser with no download required. No dedicated app is required for mobile play.',
  verdict = 'A sizeable, accessible lobby with useful free-play options and flexible banking. The regulatory framework, bonus complexity and lack of live-dealer inventory in the current public lobby prevent a higher score.',
  website_url = 'https://reddogcasino.com/',
  affiliate_url = 'https://reddogcasino.com/',
  operator_name = 'Red Dog Casino',
  operator_status = 'active',
  casino_type = 'real-money',
  established_year = 2019,
  license_authority = 'Autonomous Island of Anjouan, Union of Comoros',
  license_number = null,
  license_url = 'https://reddogcasino.com/underage-gaming-policy',
  supported_regions = array['Eligible international jurisdictions', 'Selected US states where permitted'],
  restricted_regions = array['Jurisdictions where offshore gambling is prohibited'],
  currencies = array['USD', 'CAD', 'BTC', 'ETH', 'LTC', 'USDT'],
  deposit_methods = array['Visa', 'Mastercard', 'Bitcoin', 'Ethereum', 'Litecoin', 'Tether'],
  withdrawal_methods = array['Cryptocurrency', 'Card or bank methods where available'],
  game_types = array['Slots', 'Blackjack', 'Video poker', 'Table games', 'Jackpots', 'Speciality games'],
  software_providers = array['Multiple lobby providers'],
  languages = array['English'],
  security_features = array['SSL encryption', 'Identity verification', 'Payment-method verification'],
  responsible_gambling_tools = array['Responsible-gaming policy', 'Support-assisted account controls', 'Underage-gaming policy'],
  game_count = 1662,
  minimum_deposit = 'Method-dependent',
  minimum_withdrawal = 'Method-dependent',
  withdrawal_time = 'Crypto is generally fastest; account review applies',
  wagering_requirement = 'Promotion-dependent; check current bonus terms',
  kyc_requirements = 'Government ID and payment verification may be required',
  mobile_support = 'Responsive browser; no download required',
  support_hours = '24/7 advertised',
  support_email = null,
  key_features = array['1,600+ current lobby titles', 'Free-play mode on many games', 'Card and crypto cashier', 'Responsive mobile browser'],
  pros = array['Large slot catalogue', 'Practice play is easy to find', 'Multiple payment categories', 'Clear game-category counts'],
  cons = array['Anjouan regulatory protection is limited', 'No live dealer games visible in the current lobby', 'Large bonus has complex terms', 'Payment limits vary by account'],
  rating_games = 4.2,
  rating_payments = 3.8,
  rating_withdrawals = 3.2,
  rating_support = 3.6,
  rating_safety = 2.4,
  rating_mobile = 4.0,
  faqs = '[{"question":"How many games does Red Dog offer?","answer":"The public lobby displayed roughly 1,600 titles across slots, blackjack, video poker, table games, jackpots and speciality categories during our review."},{"question":"Does Red Dog have live dealers?","answer":"A live-dealer category exists, but it displayed no public titles during our August 2026 check."},{"question":"Who licenses Red Dog?","answer":"The official site states that it is licensed by the Autonomous Island of Anjouan, Union of Comoros."}]'::jsonb,
  source_urls = array['https://reddogcasino.com/','https://reddogcasino.com/banking','https://reddogcasino.com/terms','https://reddogcasino.com/responsible-gaming','https://reddogcasino.com/underage-gaming-policy'],
  seo_title = 'Red Dog Casino review: games, bonus, payments and licence',
  seo_description = 'Independent Red Dog review covering its 1,600+ lobby titles, practice play, $8,000 welcome package, banking and Anjouan licence.',
  cta_label = 'Visit Red Dog',
  reviewed_at = date '2026-08-03',
  last_verified_at = timestamptz '2026-08-03 00:00:00+00',
  active = true,
  published = true
where slug = 'Red-Dog-Casino';

update public.online_casinos
set
  position = 4,
  rating = 4.4,
  subtitle = 'Crypto-led casino, sportsbook and mature responsible-play tools',
  bonus = 'Promotions and VIP rewards vary by region and account',
  summary = 'Stake combines a very large casino and sportsbook catalogue, fast crypto rails, 24/7 support and strong account-limit tools, with availability and licensing that vary materially by jurisdiction.',
  description = 'Stake is a global crypto-led casino and sportsbook operated by Medium Rare N.V. The casino spans slots, live dealers, table games, poker-style titles and in-house Stake Originals, while the same account also provides sports and esports betting where permitted.\n\nThe platform is polished and transparent about its game catalogue, licences and responsible-play tools. Its main limitation is jurisdictional complexity: Stake.com is not the same product as Stake.us, and access, currencies, bonuses and legal protections differ by country. Players must use the correct locally available service and verify the licence that applies to them.',
  bonus_description = 'Stake does not rely on one universal welcome headline. VIP rewards, rakeback, competitions and promotions vary by account, product and jurisdiction. Review the live promotion rules rather than relying on a third-party bonus figure.',
  deposit_description = 'The global platform is crypto-led and supports a broad selection of digital assets. Fiat on-ramps or local payment agents may be available depending on jurisdiction and account verification.',
  withdrawal_description = 'Crypto withdrawals are usually processed through the account wallet, subject to network conditions, security checks and KYC. Minimums and fees depend on the asset and network selected.',
  contact_description = 'Stake advertises real-time 24/7 live chat, a help centre and community support. Support and compliance teams handle self-exclusion and account verification.',
  security_description = 'Stake publishes its corporate entity, global licence page, AML policy, fairness information and responsible-gambling tools. Licence coverage is jurisdiction-specific, so the exact regulator and dispute route must be checked for the player’s location.',
  mobile_description = 'The responsive website is the primary experience and works well on mobile. App availability depends on platform store and jurisdiction.',
  verdict = 'The strongest all-round product in the current list for catalogue, interface, support and crypto payments. It still requires careful jurisdiction checks and disciplined use of limits because access and regulatory protection are not uniform worldwide.',
  website_url = 'https://stake.com/',
  affiliate_url = 'https://stake.com/',
  operator_name = 'Medium Rare N.V.',
  operator_status = 'restricted',
  casino_type = 'real-money',
  established_year = 2017,
  license_authority = 'Curaçao and additional regional licences',
  license_number = null,
  license_url = 'https://stake.com/licenses',
  supported_regions = array['Eligible international jurisdictions'],
  restricted_regions = array['United States for Stake.com; Stake.us is a separate sweepstakes product', 'United Kingdom', 'Other restricted jurisdictions listed in the terms'],
  currencies = array['BTC', 'ETH', 'USDT', 'USDC', 'LTC', 'DOGE', 'XRP', 'Additional supported crypto assets'],
  deposit_methods = array['Cryptocurrency', 'Jurisdiction-dependent fiat on-ramps'],
  withdrawal_methods = array['Cryptocurrency', 'Jurisdiction-dependent local methods'],
  game_types = array['Slots', 'Live casino', 'Blackjack', 'Roulette', 'Poker', 'Stake Originals', 'Sportsbook'],
  software_providers = array['Stake Engine', 'Pragmatic Play', 'Evolution', 'Play’n GO', 'Hacksaw Gaming', 'Many additional studios'],
  languages = array['English', 'Multiple international languages'],
  security_features = array['SSL encryption', 'Two-factor authentication', 'KYC and AML controls', 'Published fairness information'],
  responsible_gambling_tools = array['Deposit limits', 'Loss limits', 'Wager limits', 'Cooling-off periods', 'Break in play', 'Self-exclusion', 'Budget calculator'],
  game_count = null,
  minimum_deposit = 'Asset- and network-dependent',
  minimum_withdrawal = 'Asset- and network-dependent',
  withdrawal_time = 'Usually fast for crypto after security checks; network-dependent',
  wagering_requirement = 'Promotion-dependent',
  kyc_requirements = 'Identity verification is jurisdiction- and risk-dependent and may be required before withdrawal',
  mobile_support = 'Responsive browser; app availability varies',
  support_hours = '24/7 live chat',
  support_email = 'support@stake.com',
  key_features = array['Casino and sportsbook', 'Extensive crypto support', 'Stake Originals', '24/7 live chat', 'Detailed limit and self-exclusion tools'],
  pros = array['Excellent catalogue breadth', 'Polished desktop and mobile interface', 'Strong crypto wallet experience', 'Wide responsible-play toolset', 'Clear corporate and licence pages'],
  cons = array['Not available in every jurisdiction', 'Stake.com and Stake.us are different products', 'Crypto price and network risk', 'Bonus and KYC rules vary by account'],
  rating_games = 4.9,
  rating_payments = 4.6,
  rating_withdrawals = 4.4,
  rating_support = 4.5,
  rating_safety = 4.0,
  rating_mobile = 4.7,
  faqs = '[{"question":"Is Stake licensed?","answer":"Stake publishes Curaçao and additional regional licences on its official licence page. The licence that applies depends on your location."},{"question":"Is Stake.com available in the United States?","answer":"Stake.com is not the US product. Stake.us is a separate sweepstakes platform with different rules and currencies."},{"question":"What responsible-gambling tools are available?","answer":"The account includes deposit, loss and wager limits, cooling-off, breaks in play and self-exclusion options."}]'::jsonb,
  source_urls = array['https://stake.com/','https://stake.com/licenses','https://stake.com/casino/home','https://stake.com/policies/self-exclusion','https://stake.com/blog/stake-customer-support-guide'],
  seo_title = 'Stake Casino review: games, crypto, licences and safety',
  seo_description = 'Detailed Stake Casino review covering games, crypto payments, licences, 24/7 support, responsible-play tools and regional restrictions.',
  cta_label = 'Visit Stake',
  reviewed_at = date '2026-08-03',
  last_verified_at = timestamptz '2026-08-03 00:00:00+00',
  active = true,
  published = true
where slug = 'Stake-Casino';

update public.online_casinos
set
  position = 5,
  rating = 4.2,
  subtitle = 'Established sweepstakes casino with 1,500+ games',
  bonus = 'Free daily rewards; optional coin packages vary',
  summary = 'High 5 Casino is a mature US sweepstakes platform with more than 1,500 games, daily free rewards, card and Apple Pay purchases, prize redemptions and native iOS/Android apps.',
  description = 'High 5 Casino is a sweepstakes and social casino operated by High Entertainment, LLC. It uses Game Coins for entertainment and Sweeps Coins for prize-eligible play; Sweeps Coins can be obtained through free entry routes and promotional rewards rather than being sold directly.\n\nThe platform stands out for its scale, long-running game studio background and native mobile apps. It is not a conventional real-money casino and should not be compared directly with regulated deposit casinos: state eligibility, coin playthrough and prize-redemption rules are the key points to review.',
  bonus_description = 'Free sign-up and daily rewards change over time. The operator also sells Game Coin packages that can include promotional Sweeps Coins and Diamonds. No purchase is necessary for sweepstakes entry; consult the official rules and AMOE instructions.',
  deposit_description = 'There is no conventional casino deposit. Players may purchase Game Coin packages using cards and Apple Pay where available, with promotional Sweeps Coins included on eligible packages.',
  withdrawal_description = 'Eligible Sweeps Coins can be redeemed for prizes after identity verification and required playthrough. Available redemption methods and timing depend on the account, activity and location.',
  contact_description = 'High 5 provides a detailed help centre and email support. Verification, eligibility and redemption issues are handled through the account support flow.',
  security_description = 'The sweepstakes model is governed by official rules rather than a real-money casino licence. High 5 publishes eligibility, no-purchase entry, verification and responsible-play information.',
  mobile_description = 'High 5 provides both responsive web play and native iOS/Android apps, with the same dual-currency account and game library.',
  verdict = 'One of the most complete sweepstakes products in the current list, particularly for catalogue size, mobile apps and free entry routes. Players must understand the coin model and state restrictions before purchasing packages or seeking prize redemption.',
  website_url = 'https://high5casino.com/',
  affiliate_url = 'https://high5casino.com/',
  operator_name = 'High Entertainment, LLC',
  operator_status = 'restricted',
  casino_type = 'sweepstakes',
  established_year = 2013,
  license_authority = 'US sweepstakes model; governed by official sweepstakes rules',
  license_number = null,
  license_url = 'https://high5casino.com/sweepstakes/',
  supported_regions = array['Eligible US states'],
  restricted_regions = array['States and territories excluded by the current official rules'],
  currencies = array['Game Coins', 'Sweeps Coins', 'Diamonds', 'USD for optional Game Coin packages'],
  deposit_methods = array['Credit card', 'Debit card', 'Apple Pay'],
  withdrawal_methods = array['Eligible prize-redemption methods shown in account'],
  game_types = array['Slots', 'Jackpots', 'Table games', 'Social casino games'],
  software_providers = array['High 5 Games', 'Additional partner studios'],
  languages = array['English'],
  security_features = array['Identity verification', 'Location eligibility controls', 'Account security controls'],
  responsible_gambling_tools = array['Free no-purchase entry', 'Responsible-play tools', 'Support-assisted account controls', 'State eligibility checks'],
  game_count = 1500,
  minimum_deposit = 'No deposit; optional Game Coin packages',
  minimum_withdrawal = 'Redemption threshold shown in the verified account',
  withdrawal_time = 'Account- and verification-dependent',
  wagering_requirement = 'Sweeps Coins must satisfy the current playthrough rules before redemption',
  kyc_requirements = 'Identity and location verification before prize redemption',
  mobile_support = 'Responsive web plus native iOS and Android apps',
  support_hours = 'Help centre and email support',
  support_email = 'support@high5casino.com',
  ios_url = 'https://high5casino.com/sweepstakes/app/',
  android_url = 'https://high5casino.com/sweepstakes/app/',
  key_features = array['1,500+ games', 'Free daily rewards', 'No-purchase sweepstakes entry', 'iOS and Android apps', 'Card and Apple Pay packages'],
  pros = array['Very large sweepstakes catalogue', 'Established game-studio background', 'Native apps and responsive web', 'Clear free-entry routes', 'Daily rewards'],
  cons = array['Not a conventional real-money casino', 'Availability varies by US state', 'Coin model can be confusing', 'Redemption requires verification and playthrough'],
  rating_games = 4.7,
  rating_payments = 4.2,
  rating_withdrawals = 3.8,
  rating_support = 4.0,
  rating_safety = 4.1,
  rating_mobile = 4.7,
  faqs = '[{"question":"Is High 5 Casino a real-money casino?","answer":"No. It is a sweepstakes/social casino using Game Coins and Sweeps Coins. Eligible Sweeps Coins can be redeemed for prizes under the official rules."},{"question":"Is a purchase required?","answer":"No. High 5 publishes no-purchase entry methods and daily free rewards. Optional Game Coin packages are available."},{"question":"Does High 5 have a mobile app?","answer":"Yes. The operator provides native iOS and Android apps as well as browser play."}]'::jsonb,
  source_urls = array['https://high5casino.com/','https://high5casino.com/sweepstakes/','https://high5casino.com/helpcenter/how-to-get-free-sweeps-coins/','https://high5casino.com/helpcenter/how-to-redeem-real-prizes/','https://high5casino.com/sweepstakes/app/'],
  seo_title = 'High 5 Casino review: games, Sweeps Coins and redemptions',
  seo_description = 'High 5 Casino review covering 1,500+ games, free Sweeps Coins, optional packages, prize redemptions, state restrictions and mobile apps.',
  cta_label = 'Visit High 5 Casino',
  reviewed_at = date '2026-08-03',
  last_verified_at = timestamptz '2026-08-03 00:00:00+00',
  active = true,
  published = true
where slug = 'High-5-Casino';

update public.online_casinos
set website_url = affiliate_url
where website_url = '' and affiliate_url <> '';
